name: local_multininja_backend

services:
  multi-ninja.backend.writemodel.local:
    container_name: multi-ninja.backend.writemodel.local
    hostname: multi-ninja.backend.writemodel.local
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_DATABASE=write_model
      - MYSQL_USER=multi-ninja-writes
      - MYSQL_PASSWORD=multi-ninja-writes-password
    volumes:
      - type: volume
        source: writemodel-data
        target: /var/lib/mysql
    ports:
      - 10001:3306

  # multi-ninja.backend.local:
    # container_name: multi-ninja.backend.local
    # hostname: multi-ninja.backend.local
    # image: multi-ninja-backend:local
    # restart: always
    # environment:
      # - ConnectionStrings__WriteDatabase=Server=multi-ninja.backend.writemodel.local;Port=3306;Database=write_model;Uid=multi-ninja-writes;Pwd=multi-ninja-writes-password;
    # ports:
      # - 10003:8080
    # depends_on:
      # - multi-ninja.backend.writemodel.local

  # multi-ninja.frontend.local:
    # container_name: multi-ninja.frontend.local
    # hostname: multi-ninja.frontend.local
    # image: multi-ninja-frontend:local
    # restart: always
    # ports:
      # - 10004:80
    # depends_on:
      # - multi-ninja.backend.local

  multi-ninja.backend.writemodeladmin.local:
    container_name: multi-ninja.backend.writemodeladmin.local
    hostname: multi-ninja.backend.writemodeladmin.local
    image: phpmyadmin:5.2.2
    restart: always
    environment:
      - PMA_HOST=multi-ninja.backend.writemodel.local
    ports:
      - 10002:80
    depends_on:
      - multi-ninja.backend.writemodel.local

volumes:
  writemodel-data: