name: local_multininja_backend

services:
  multi-ninja.backend.writemodel.local:
    container_name: multi-ninja.backend.writemodel.local
    hostname: multi-ninja.backend.writemodel.local
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_DATABASE=write_model
      - MYSQL_USER=multi-ninja-writes
      - MYSQL_PASSWORD=multi-ninja-writes-password
    volumes:
      - type: volume
        source: writemodel-data
        target: /var/lib/mysql
    ports:
      - 10001:3306
    profiles:
      - storage
      - full

  multi-ninja.backend.readmodel.local:
    container_name: multi-ninja.backend.readmodel.local
    hostname: multi-ninja.backend.readmodel.local
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_DATABASE=read_model
      - MYSQL_USER=multi-ninja-reads
      - MYSQL_PASSWORD=multi-ninja-reads-password
    volumes:
      - type: volume
        source: readmodel-data
        target: /var/lib/mysql
    ports:
      - 10002:3306
    profiles:
      - storage
      - full

  multi-ninja.backend.local:
    container_name: multi-ninja.backend.local
    hostname: multi-ninja.backend.local
    image: multi-ninja-backend:local
    restart: always
    environment:
      - ConnectionStrings__WritesDatabase=Server=multi-ninja.backend.writemodel.local;Port=3306;Database=write_model;Uid=multi-ninja-writes;Pwd=multi-ninja-writes-password;
      - ConnectionStrings__ReadsDatabase=Server=multi-ninja.backend.readmodel.local;Port=3306;Database=read_model;Uid=multi-ninja-reads;Pwd=multi-ninja-reads-password;
    ports:
      - 10003:8080
    depends_on:
      - multi-ninja.backend.writemodel.local
      - multi-ninja.backend.readmodel.local
      - multi-ninja.keycloak.local
    profiles:
      - full

  multi-ninja.frontend.local:
    container_name: multi-ninja.frontend.local
    hostname: multi-ninja.frontend.local
    image: multi-ninja-frontend:local
    restart: always
    ports:
      - 10004:80
    depends_on:
      - multi-ninja.backend.local
    profiles:
      - full

  multi-ninja.backend.dbadmin.local:
    container_name: multi-ninja.backend.dbadmin.local
    hostname: multi-ninja.backend.dbadmin.local
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - 10005:80
    volumes:
      - type: bind
        source: .\docker_files\dbadmin\config.user.inc.php
        target: /etc/phpmyadmin/config.user.inc.php
    depends_on:
      - multi-ninja.backend.writemodel.local
    profiles:
      - storage
      - full

  multi-ninja.keycloak.storage.local:
    container_name: multi-ninja.keycloak.storage.local
    hostname: multi-ninja.keycloak.storage.local
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak-password
    volumes:
      - type: volume
        source: keycloak-data
        target: /var/lib/mysql
    profiles:
      - storage
      - full

  multi-ninja.keycloak.local:
    container_name: multi-ninja.keycloak.local
    hostname: multi-ninja.keycloak.local
    image: quay.io/keycloak/keycloak:24.0.3
    command: start
    depends_on:
      - multi-ninja.keycloak.storage.local
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_DB: mysql
      KC_DB_URL_HOST: multi-ninja.keycloak.storage.local
      KC_DB_URL_PROPERTIES : '?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true'
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 'keycloak-password'
    ports:
      - 10006:8080
    restart: always
    profiles:
      - storage
      - full

volumes:
  writemodel-data:
  readmodel-data:
  keycloak-data:
  keycloak_data:
