// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiNinja.Backend.Infrastructure.WritesRepository.EfCore;

#nullable disable

namespace MultiNinja.Backend.WritesDatabase.Migrations
{
    [DbContext(typeof(WriteContext))]
    partial class WriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MultiNinja.Backend.Infrastructure.WritesRepository.EfCore.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("SerializedEvent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("Version")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("EventId");

                    b.HasIndex("StreamId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MultiNinja.Backend.Infrastructure.WritesRepository.EfCore.ProcessorsProgress", b =>
                {
                    b.Property<string>("ProcessorName")
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("LastProcessedPosition")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("ProcessorName");

                    b.ToTable("ProcessorProgresses");
                });

            modelBuilder.Entity("MultiNinja.Backend.Infrastructure.WritesRepository.EfCore.Stream", b =>
                {
                    b.Property<Guid>("StreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StreamId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("MultiNinja.Backend.Infrastructure.WritesRepository.EfCore.Event", b =>
                {
                    b.HasOne("MultiNinja.Backend.Infrastructure.WritesRepository.EfCore.Stream", "Stream")
                        .WithMany("Events")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("MultiNinja.Backend.Infrastructure.WritesRepository.EfCore.Stream", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
