name: Build and Test
run-name: Build and test for '${{ github.event_name}}' run on '${{ github.ref_name }}'

on:
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  build-and-test-frontend:
    name: Build and test code front-end
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM packages
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Test code
        run: npm run test

  build-and-test-backend:
    name: Build and test code back-end
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"

    - name: Publish test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
